---
- name: Installer
  hosts: all
  gather_facts: yes

  vars_files:
    - vars.yml

  roles:
    - install_packages
    - clone_git_repo
    - create_system_user
    - start_nodejs_app
    - copy_nginx_config
    - ensure_httpd_stopped
    - start_nginx_service

